ROOT_DIR = ../..

include $(ROOT_DIR)/make_vars

.PHONY: tmp
tmp:
	cd list; make
	cd stack; make
	cd queue; make
	cd multiset; make
	cd set; make
	cd digraph; make;
	cd map; make;
	cd graph; make;

	cd isort; make
	cd bubblesort; make
	cd dfs; make

